/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#ifndef __CPARSER_TREE_H__
#define __CPARSER_TREE_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

extern cparser_node_t cparser_root;

cparser_result_t cparser_cmd_show_employees(cparser_context_t *context);
cparser_result_t cparser_cmd_show_employees_all(cparser_context_t *context);
cparser_result_t cparser_cmd_show_employees_by_id_min_max(cparser_context_t *context,
    uint32_t *min_ptr,
    uint32_t *max_ptr);
cparser_result_t cparser_cmd_show_employee_id_field(cparser_context_t *context,
    uint32_t *id_ptr,
    char **field_ptr);
cparser_result_t cparser_cmd_show_employee_id_bonus_factor(cparser_context_t *context,
    uint32_t *id_ptr);
cparser_result_t cparser_cmd_employee_id(cparser_context_t *context,
    uint32_t *id_ptr);
cparser_result_t cparser_cmd_emp_exit(cparser_context_t *context);
cparser_result_t cparser_cmd_emp_name_name(cparser_context_t *context,
    char **name_ptr);
cparser_result_t cparser_cmd_emp_date_of_birth_month_day_year(cparser_context_t *context,
    int32_t *month_ptr,
    int32_t *day_ptr,
    int32_t *year_ptr);
cparser_result_t cparser_cmd_emp_height_inches(cparser_context_t *context,
    uint32_t *inches_ptr);
cparser_result_t cparser_cmd_emp_weight_lbs(cparser_context_t *context,
    uint32_t *lbs_ptr);
cparser_result_t cparser_cmd_emp_bonus_factor_scale(cparser_context_t *context,
    double *scale_ptr);
cparser_result_t cparser_cmd_emp_pc_ip_address_ipv4(cparser_context_t *context,
    uint32_t *ipv4_ptr);
cparser_result_t cparser_cmd_emp_pc_mac_address_addr(cparser_context_t *context,
    cparser_macaddr_t *addr_ptr);
cparser_result_t cparser_cmd_emp_title_title(cparser_context_t *context,
    char **title_ptr);
cparser_result_t cparser_cmd_emp_passcode_passcode(cparser_context_t *context,
    uint64_t *passcode_ptr);
cparser_result_t cparser_cmd_emp_help_filter(cparser_context_t *context,
    char **filter_ptr);
cparser_result_t cparser_cmd_no_employee_id(cparser_context_t *context,
    uint32_t *id_ptr);
cparser_result_t cparser_cmd_save_roster_filename(cparser_context_t *context,
    char **filename_ptr);
cparser_result_t cparser_cmd_load_roster_filename(cparser_context_t *context,
    char **filename_ptr);
cparser_result_t cparser_cmd_help_filter(cparser_context_t *context,
    char **filter_ptr);
cparser_result_t cparser_cmd_enable_privileged_mode(cparser_context_t *context);
cparser_result_t cparser_cmd_disable_privileged_mode(cparser_context_t *context);
cparser_result_t cparser_cmd_quit(cparser_context_t *context);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* __CPARSER_TREE_H__ */
